### ISSUE TITLE
[feature request] Spacemacs Light theme

### ISSUE THREAD

**Issue by ngortheone** [aaron-williamson/base16-alacritty#5]
Please add light variant of spacemacs theme!
https://github.com/nashamri/spacemacs-theme

**Comment by aarowill** [comment]
Although the official spacemacs-theme repository you linked has a light scheme, this repository uses the base16 schemes to create all of the output files. Adding a light spacemacs theme would be part of adding a base16 spacemacs scheme repository as the current spacemacs theme is unclaimed, see here: <https://github.com/chriskempson/base16-unclaimed-schemes/blob/master/spacemacs.yaml>. See the schemes section of the base16 readme for more on how to add a new scheme: <https://github.com/chriskempson/base16#scheme-repositories>.

If you or someone else adds a light spacemacs scheme, I would be happy to run the build and include those output files here. Feel free to open a PR or another issue for a rebuild if that happens, but I'm going to close this issue as it's something that should be resolved elsewhere.
